### ISSUE TITLE
Improve crosswalk from schema.org to oai_dc

### ISSUE THREAD

**Issue by sneumann** [NFDI4Chem/oai4schemas#1]
Since OAI-PMH mandates the metadataPrefix `oai_dc`, there is a crosswalk 
from schema.org to `oai_dc` via `xslt` in [json_container2oai_dc.xslt](https://github.com/NFDI4Chem/oai4chem/blob/main/json_container2oai_dc.xslt)

=> The crosswalk is currently very minimalistic and needs improvement. 
This ressource gives background on crosswalks: https://doi.org/10.5281/zenodo.4420116

The minimalistic example we have is 
```
<oai_dc:dc xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:json="http://denbi.de/schemas/json-container" xmlns:map="http://www.w3.org/2005/xpath-functions/map" xmlns:oai_dc="http://www.openarchives.org/OAI/2.0/oai_dc/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/oai_dc/ https://www.openarchives.org/OAI/2.0/oai_dc.xsd http://purl.org/dc/elements/1.1/ https://www.radar-service.eu/schemas/dc.xsd">
  <dc:identifier>https://massbank.eu/MassBank/RecordDisplay?id=MSBNK-Eawag-EQ358855#HHZIURLSWUIHRB-UHFFFAOYSA-N</dc:identifier>
  <dc:identifier>DOI</dc:identifier>
  <oai_dc:title>Nilotinib</oai_dc:title>
</oai_dc:dc>
```

**Comment by febach** [comment]
I will have a look at it with Sandra!

**Comment by sneumann** [comment]
Hi, to reproduce the issue / task, I have the following code snippet:
`./any-jsonld2json_container.sh data/MSBNK-Eawag-EA00040-MolecularEntity.json | java -jar /usr/share/java/Saxon-HE-9.9.1.5.jar -xsl:json_container2oai_dc.xslt -s:- `

which will create the following almost-oai_dc XML output:
```
<oai_dc:dc xmlns:dc="http://purl.org/dc/elements/1.1/"
           xmlns:oai_dc="http://www.openarchives.org/OAI/2.0/oai_dc/"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xmlns:map="http://www.w3.org/2005/xpath-functions/map"
           xmlns:json="http://denbi.de/schemas/json-container"
           xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/oai_dc/ https://www.openarchives.org/OAI/2.0/oai_dc.xsd http://purl.org/dc/elements/1.1/ https://www.radar-service.eu/schemas/dc.xsd">
   <dc:identifier>https://massbank.eu/MassBank/RecordDisplay?id=MSBNK-Eawag-EA000401#OUSYWCQYMPDAEO-UHFFFAOYSA-N</dc:identifier>
   <dc:identifier>DOI</dc:identifier>
   <oai_dc:title>Metamitron-desamino</oai_dc:title>
</oai_dc:dc>
```
I'd like to ask for two things from @febach or @stefanbozic or someone else:
1) please provide here in the issue a command line to validate that oai_dc XML output, and see what is actually broken. Maybe with an `xmllint` call against a oai_dc XSD ? And where to find that XSD ? 
2) please suggest a fix to https://github.com/NFDI4Chem/oai4schemas/blob/main/json_container2oai_dc.xslt so that the validation succeeds.

Thanks in advance, 
yours, Steffen

**Comment by stefanbozic** [comment]
Hi Steffen,

instead of
<oai_dc:title>Metamitron-desamino</oai_dc:title>

please use
<dc:title>Metamitron-desamino</dc:title>

Then the validation is successful.

You can use an online validator for verification.
https://www.freeformatter.com/xml-validator-xsd.html

Sorry to provide no fix at the moment.

Regards Stefan

**Comment by sneumann** [comment]
Excellent, thanks for the hint. Fix will come shortly.

A commandline alternative for the validation is:
Since the `<oai_dc:dc>` version of the metadata is embedded in the `<OAI-PMH>` response,
for the validation and use it needs to be extracted and piped into the validation
or some other consumer:

```
xmllint --xpath '//*[namespace-uri()="http://www.openarchives.org/OAI/2.0/oai_dc/" and local-name()="dc"]' \
  examples/oai_dc-MIIFHRBUBUHJMC-UHFFFAOYSA-N.1.xml  |\
  xmllint --schema oai_dc.xsd -
```
I was unable to find a command line version that validates and downloads the XSDs from the schema locations mentioned in the XML. 

Yours, Steffen
